### ISSUE TITLE
Pip error when trying to install any package with pipman

### ISSUE THREAD

**Issue by nickcorona** [sollidsnake/pipman#18]
pipman: Preparing virtualenv
pipman: Installing 'plotly' in virutalenv
Traceback (most recent call last):
  File "/usr/bin/pipman", line 79, in <module>
    action(args, quiet)
  File "/usr/bin/pipman", line 52, in install
    Pip2Pkgbuild(packages, quiet=quiet).install_all(dir)
  File "/usr/lib/python3.7/site-packages/pipman/pip2pkgbuild.py", line 80, in __init__
    self.install_in_venv(pack)
  File "/usr/lib/python3.7/site-packages/pipman/pip2pkgbuild.py", line 188, in install_in_venv
    '--disable-pip-version-check', package])
  File "/usr/lib/python3.7/site-packages/pipman/pip2pkgbuild.py", line 92, in _exec
    func(command)
  File "/usr/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pipman/pipman-venv/bin/pip': '/tmp/pipman/pipman-venv/bin/pip'

**Comment by sollidsnake** [comment]
I can't reproduce this error on my machine, but it seems there's a problem with your pipman's virtualenv. Please try deleting the `/tmp/pipman` directory and running it again. Let me know if that works.

**Comment by nickcorona** [comment]
> I can't reproduce this error on my machine, but it seems there's a problem with your pipman's virtualenv. Please try deleting the `/tmp/pipman` directory and running it again. Let me know if that works.

That worked. Thanks, @sollidsnake.
