### ISSUE TITLE
Is there a way to remove packages with pipman?

### ISSUE THREAD

**Issue by nickcorona** [sollidsnake/pipman#19]
When I run pipman -Su, it tries to update packages I've removed with pacman. I don't want to update these packages.

Example:
```
❯ pipman -Su
pipman: Checking package info
Traceback (most recent call last):
  File "/usr/bin/pipman", line 79, in <module>
    action(args, quiet)
  File "/usr/bin/pipman", line 60, in update
    InstallData().check_updates(quiet)
  File "/usr/lib/python3.7/site-packages/pipman/pip2pkgbuild.py", line 47, in check_updates
    info = Pip2Pkgbuild.compile_package_info(pack[1]['name'])
  File "/usr/lib/python3.7/site-packages/pipman/pip2pkgbuild.py", line 251, in compile_package_info
    stderr=DEVNULL)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/pipman/pipman-venv/bin/pip', 'show', 'trypackage']' returned non-zero exit status 1.
```

**Comment by sollidsnake** [comment]
I see, I'm gonna have to fix this by checking if the package exists in pacman's repo before updating. Until then you can remove it manually editing the file `~/.local/share/pipman/data.json`.

**Comment by sollidsnake** [comment]
Sorry for taking so long, I've busy with other things lately. I just pushed a commit that should fix this, along with other improvements for the updates. Can you please try it again now?
