### ISSUE TITLE
ENCODING can be None

### ISSUE THREAD

**Issue by charles-dyfis-net** [sollidsnake/pipman#9]
```
$ LC_ALL=C LANG=en_US python -i ./pipman wal-e
pipman: Preparing virtualenv
pipman: Installing 'wal-e' in virutalenv
Requirement already satisfied: wal-e in /tmp/pipman/pipman-venv/lib/python3.4/site-packages
Requirement already satisfied: gevent>=1.1.1 in /tmp/pipman/pipman-venv/lib/python3.4/site-packages (from wal-e)
Requirement already satisfied: greenlet>=0.4.10 in /tmp/pipman/pipman-venv/lib/python3.4/site-packages (from gevent>=1.1.1->wal-e)
Traceback (most recent call last):
  File "./pipman", line 73, in <module>
    action(args, quiet)
  File "./pipman", line 39, in generate
    Pip2Pkgbuild(packages, quiet=quiet).generate_all(dir)
  File "/data/build/VC/pipman/src/pipman/pip2pkgbuild.py", line 31, in __init__
    self.install_in_venv(pack)
  File "/data/build/VC/pipman/src/pipman/pip2pkgbuild.py", line 135, in install_in_venv
    dependencies = dependencies.decode(ENCODING)
TypeError: decode() argument 1 must be str, not None
>>> import locale
>>> locale.getdefaultlocale()
(None, None)
>>>
```

**Comment by sollidsnake** [comment]
Fixed on a5bd486. If no encoding found, it's gonna use utf8. Thanks for reporting.
